### ISSUE TITLE
Select Data is not working with knockout 3.3

### ISSUE THREAD

**Issue by ZouZou** [shaftware/knockout-select2#1]
I have downloaded the code, linked it to jquery-1.11 and knockout 3.3.0 and as it seems the select data is not working. Am I missing something?

**Comment by cruikshj** [comment]
Please provide an example that is not working.  Select2 can be tricky.

**Comment by cruikshj** [comment]
Looks like the problem is specifically with knockout 3.3... i will be looking into it further.

**Comment by cruikshj** [comment]
Found the issue...   prior to 3.3, the subscription object exposed the binding as "target"... in 3.3 it changed to "_target".  I have modified my handler to account for either.

d904767bcd9aa4db90d4334a0467cb46621a03d3

**Comment by ZouZou** [comment]
That's great I will try it out tomorrow
